snyk/snyk-iac-rules

.github/workflows/release.yml
.goreleaser.yml

This PR adds the Homebrew, Scoop, and NFPMS release
The configuration is based off of: https://goreleaser.com/customization/scoop/ and https://goreleaser.com/customization/homebrew/.
The tap for homebrew is https://github.com/snyk/homebrew-tap
The bucket for scoop is https://github.com/snyk/scoop-snyk
Since these are owned by Hammer, we need to await their approval from https://snyk.slack.com/archives/C0127HWU0E7/p1632404109085600.
- [Jira ticket CFG-327](https://snyksec.atlassian.net/browse/CFG-327)
- [Link to documentation](https://www.notion.so/snyk/Release-process-2b7b25f9ae524805b5b5f3327835bb90#eb3ec89833d542bfbc53c0380085944f)

chore: homebrew, scoop, nfpms releases [CFG-327]

---

.github/workflows/release.yml

NPM Publish failed because we didn't switch directory before trying the run step. We need to cd into the dist/ directory first and then call the npm publish, else GH won't find the package.json file. 
Example of failure: https://github.com/snyk/snyk-iac-rules/runs/3767725322?check_suite_focus=true
Structure:
```
.
├── dist
│   ├── package.json
│   ├── snyk-iac-rules
│   ├── snyk-iac-rules-darwin-amd64
│   ├── snyk-iac-rules-darwin-arm64
│   ├── snyk-iac-rules-linux-amd64
│   ├── snyk-iac-rules-linux-arm64
│   └── snyk-iac-rules.exe
├── packaging
│   └── npm
│       ├── package.json.in
│       └── passthrough.js
├── scripts
│   ├── install-shellspec-win.sh
│   ├── release-github.sh
│   ├── release-npm.sh
│   ├── run-contract-win.sh
│   └── run-e2e-win.sh
├── snyk-iac-rules
37 directories, …
```

chore: Update workflow to publish npm

---

RELEASE.md
packaging/npm/package.json.in

Renames the github repo url for the generation of the package json. NPM registry should point to the correct repo url: https://www.npmjs.com/package/snyk-iac-rules

chore: Update package.json with correct github url

---

.github/workflows/release.yml

This will edit the workflow to first get the new tag, and only if that exists, generate the releases (to github, brew, scoop, npm).
If it doesn't exist, we expect the pipeline to just skip the release steps and not fail, like it does now.

fix: Skip releases if there is no new tag

---

cmd/template.go
spec/e2e/build_spec.sh
spec/e2e/help_spec.sh
spec/e2e/parse_spec.sh
spec/e2e/push_spec.sh
spec/e2e/template_spec.sh
spec/e2e/test_spec.sh

This PR fixes a small mistake in the `template` command where the shorthand options are mixed up. It also includes some shellspec testing to cover testing these options.

fix: template options in --help output

---

action.yml

This PR adds an action that will be exposed by this repository to setup our environment for shellspec testing. It will be used by a future GitHub action to setup the environment for each of our supported registries. It is required so we don't introduce duplication in our GitHub actions. The supported registries will be tested using `shellspec`, which allows us to test the end-to-end flow from pushing a bundle to pulling it with the snyk CLI. 
This action was written based on:
- https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
- https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/
It will be exposed from this repository and used as such:
```
- name: Setup
uses: actions/snyk-iac-rules@v1
```
I haven't been able to …

chore: add action to be used by registry testing

---

cmd/build.go
cmd/template.go
cmd/test.go
spec/contract/snyk_spec.sh

This PR removes some extra logic we added in case `.` does not work in Windows. The contract and e2e tests run the SDK against Windows, Linux, and MacOS so I **think** they would complain if the `.` was a problem.

fix: remove custom code for os-specific path

---

.github/actions/setup_shellspec/action.yml
.github/workflows/contract.yml
.github/workflows/main.yml
.github/workflows/registries.yml
DEVELOPMENT.md
spec/contract/snyk_spec.sh
spec/e2e/push_spec.sh
spec/registries/e2e_spec.sh
spec/support/bin/@registry_test

This ticket introduces contract tests for supported registries, verifying the `push` and `pull` from the SDK all the way to the snyk CLI. This is required for testing our supported registries, which we will document publicly in our documentation. As we add more registries to these tests, we can update the documentation too.
The documentation linked at the bottom of the description shows how to login and push the bundle, plus what credentials to use.
I've configured the tests to only run on `develop`, since we already test a full end-to-end flow and contract with DockerHub. The GitHub action ran successfully in a test run:
I've also moved the `action.yml` file once I realised I don't need to release it as an action and can use it locally (which also helped with testing).
- [Jira ticket …

test: contract test supported registries via shellspec

---

README.md

The previous PR updating the diagram in Markdown is breaking because we specified main branch.
Commenting out the url that generates the image based on the UML code. 
We need to specify the branch name and this can not happen while we are in develop/main. We need to get the branch name first if we continue using two branches. For now, we can use the rendered image instead.

docs: Comment out UML markdown, use image

---

spec/support/bin/@registry_test

In https://github.com/snyk/snyk/pull/2336 we updated the CLI to use `snyk config set` for the OCI registry environment variables. This PR updates the code in the contract test so that it works with these new env vars.
- [Jira ticket CFG-1165](https://snyksec.atlassian.net/browse/CFG-1165)

test: update env vars for snyk contract test [CFG-1165]

---

.github/workflows/release.yml

When we release a version of the SDK that only have `chore`, `test`, `refactor`, `svu` does not generate a new tag, it still uses the old tag. We then try to push it to GitHub again, causing a failure. This modifies the release workflow so that if the tag generated by the `svu` command can be found in GitHub, then we do not set the  `NEW_TAG` environment variable. The rest of the steps run if `NEW_TAG` is set, so we should not fail anymore.
**Note** I have not tested this in the workflow but I tested it locally:

chore: don't push tag if already exists

---

cmd/push.go
spec/e2e/push_spec.sh

- Prohibits adding protocols in the registry containers provided as arguments for the `push` command.
1. Prepare a custom-rules bundle generated by the [Snyk custom-rules bundles generator](https://github.com/snyk/snyk-iac-rules). You can refer to [the docs](https://app.gitbook.com/o/-M4tdxG8qotLgGZnLpFR/s/-MdwVZ6HOZriajCf5nXH/c/rcGL1hZooMgd9mG27qkq/products/snyk-infrastructure-as-code/custom-rules/getting-started-with-the-sdk) to learn how.
2. Push the generated bundle to an OCI registry, using a registry container path that contains a protocol (e.g.,  `https://registry/library/image:tag`). You can folllow in [these instructions](https://docs.snyk.io/products/snyk-infrastructure-as-code/custom-rules/getting-started-with-the-sdk/pushing-a-bundle) for pushing a custom rules bundle.
3. …

fix: Prohibited protocols in registries for push.

---

cmd/build.go
cmd/test.go
spec/e2e/build_spec.sh
spec/e2e/test_spec.sh
util/file_system.go
util/file_system_test.go

This PR makes two changes:
1. The `test` and `build `command accept multiple paths, so that users of the SDK can point at the exact folders they have their rules and helper functions in
2. The two commands use `rules/` and `lib/` as the default paths for the above change, so that it works from the get go
There's a bit of duplication but other than pulling 
```
if len(args) == 0 {
// add default path if not provided
args = append(args, "rules/", "lib/")
}
```
into a function I can't think of a nice way to de-duplicate while still keeping the code readable.
Suggestions are welcome.
- [Slack thread](https://snyk.slack.com/archives/CMM9V3XPY/p1637910095232200)

fix: add default paths for rules/ and lib/ folder

---

spec/contract/snyk_spec.sh

- Adds tests for the existence of the new user message added to the Snyk CLI for custom rules.
When users apply custom rules bundles in the Snyk CLI, a new message now appears: "Using custom rules to generate misconfigurations.".
We'd like to add this message to our contract tests.
- [PR with user message](https://github.com/snyk/snyk/pull/2393)
- [Slack thread](https://snyk.slack.com/archives/C022H54L8PJ/p1638293346269500)

test: Add custom rules message to e2e tests

---

.github/workflows/main.yml
packaging/npm/passthrough.js
scripts/release-npm.sh

Fixes 'npm install' E2E tests on MacOS.
Fixed 'npm install' E2E tests on Windows, Windows test did not run(or show the output) snyk-iac-rules binary
- [Jira ticket CFG-1250](https://snyksec.atlassian.net/browse/CFG-1250)

fix: npm package installation for npm 16.x

---

spec/contract/snyk_spec.sh
util/file_system.go
util/file_system_test.go

If the user provides a path like `rules/` then we would throw a warning. Instead of checking the path has a suffix, instead we compute the base of the path and see if it's `rules`

fix: check for rules folder in current path

---

fixtures/custom-rules/rules/CUSTOM-4/main.rego

Forgot a `trace` in the rego rule and it was causing the CLI to fail with the following message:
These tests run in `develop` only so that's why we didn't catch the failure inside a PR.

chore: fix registries tests

---

builtins/hcl.go
builtins/terraform_plan.go
builtins/yaml.go
go.mod
go.sum
internal/parse.go

This PR refactors the `snyk-iac-parsers` import after the functions were moved to the top-level of the Golang module.

refactor: snyk-iac-parsers import

---

internal/template.go
internal/template_test.go
spec/e2e/template_spec.sh
util/templates/fixtures/denied.json.tfplan
util/templates/main_test.tpl.rego
util/templating_test.go

This PR adds a fixture file example for Terraform Plan JSON output. The aim is to show what name the file must have (i.e. file extension `json.tfplan`), however the public docs will explain that the contents of the file itself will come from Terraform. The fixture file is also used in the actual tests so we know that when someone generates a new rule, all our formats are supported and tested from the beginning.
- [Jira ticket CFG-1204](https://snyksec.atlassian.net/browse/CFG-1204)

feat: add terraform plan fixture example [CFG-1204]

---

.goreleaser.yml

This is part of our OSS license compliance, we need to include the licence/copyright information and in the case of the MPL2.0 licence for hashicorp/hcl the entire sourcecode alongside our distribution. Fortunately the [go-licenses](https://github.com/google/go-licenses) package handles this for us and will generate a directory containing all the relevant documents to comply with the dependency licences. We then tarball this and include it with the releases.
I've tested this locally by running:
goreleaser release --snapshot --rm-dist
Which confirms the tarball is created correctly, what I cannot confirm, but have reasonable confidence will work is the final `release.extra_files` step which should then upload the acknowledgements.tar.gz alongside the other files in the release.  
- …

Include acknowledgements.tar.gz with release [CFG-1245]

---

cmd/template.go
main.go
spec/e2e/push_spec.sh
spec/e2e/template_spec.sh

This PR has two changes:
1. Extra validation of the rule name, so it accounts for capitalisation
2. Removes extra logging so that we don't print out double the errorlogs
This changes what gets printed out but since the error log was just duplicated we don't think this requires a major version release.
- Before
- After

fix: remove extra error log

---

.circleci/config.yml

Switching env variable source to circle ci context

chore: use circle context for env

---

util/inspect.go
util/inspect_test.go

This functionality was first introduced in https://github.com/snyk/snyk-iac-rules/pull/121 but that PR is blocked behind a bug in OPA. This PR extracts the utility function from that PR, which just retrieves the `publicId`s for all rego rules in a bundle - including duplicates.
- OPA introduced a new command called `inspect` which helps us find all the rego rules in a folder: https://github.com/open-policy-agent/opa/blob/main/cmd/inspect.go
- The majority of the code is not exposed in the Golang module so we are adapting a couple lines to read all the rego rules in a folder.
- The `inspect` command only looks at files and not the contents -  but we need a way to get the `publicId`
- The way we get the `publicId` is by reading each file and using a regex to extract the `publicId` which …

chore: add utility function for retrieving the rules in a bundle [CFG-1291]

---

Dockerfile

This PR adds a specific working directory to the docker image.
The change will enable us to run the SDK as a container while linking it to the local directory of the user by using:
`docker run --rm --mount source=$PWD,target=/app,type=bind snyk/snyk-iac-rules`

fix: add WORKDIR to the Dockerfile

---

Dockerfile

This PR fixes the docker image by moving the snyk-iac-rules binary to a directory that is included in the PATH of the user (usr/local/bin).

Fix the COPY and ENTRYPOINT in the Dockerfile

---

.circleci/config.yml

Adds a job to CircleCI for linting commit messages using https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional
The release process uses https://github.com/caarlos0/svu to create releases so it's important that we don't allow invalid commits through.
Failed for a `test commit`:
Succeeded for current commit:

chore: add job to lint commits

---

.goreleaser.yml
README.md

As part of the [instructions for securing container images published by Snyk](https://www.notion.so/snyk/Securing-container-images-published-by-Snyk-7c4863303572442bb5c3b96efc6184a5#7cbbe1b708a04d88ad98967e6c9eb8a8), we'd like to ensure that the [snyk/snyk-iac-rules](https://hub.docker.com/r/snyk/snyk-iac-rules) image contains only semver versions.
In order to accomplish that, we will make sure the `latest` tag is not used anywhere so that we can safely delete it on Docker Hub.
Instead, we will reference the actual latest version's tag, which is `1.2.0`.
[Jira ticket CFG-1267](https://snyksec.atlassian.net/browse/CFG-1267)
[Slack thread](https://snyk.slack.com/archives/CS61093QC/p1638959678001800)
[Notion - Securing container images published by …

chore: Specified the container latest version [CFG-1267]

---

.goreleaser.yml
README.md

- Reverts the changes from this #136, by re-adding the `latest` tag to the release flow for the `snyk/snyk-iac-rules` image.
- Following a discussion with the [#proj-secure-public-client-images](https://snyk.slack.com/archives/C02GCNHTUAU) channel members, it has been confirmed that the `latest` tag for [snyk/snyk-iac-rules](https://hub.docker.com/repository/docker/snyk/snyk-iac-rules) can still be published as part of our release pipeline, as long as the semver versions for the image are updated correctly.
- It was originally removed as part of the instructions for [securing container images published by Snyk](https://www.notion.so/snyk/Securing-container-images-published-by-Snyk-7c4863303572442bb5c3b96efc6184a5#7cbbe1b708a04d88ad98967e6c9eb8a8), which recommend supporting only semver …

Chore: Re-added latest tag for docker image

---

internal/build.go
internal/build_test.go
util/inspect.go
util/inspect_test.go

- Asserts the inexistence of rules with the same public ID when building bundles. 
There is currently no validation to make sure a new rule doesn’t have the same public ID as an existing one. We have some in the template command - the rule id is used for the folder name so we error if the folder already exists. But we don’t stop users from changing the id afterward.
We'd like to ensure that generated bundles do not contain duplicate rules, that is, rules with the same public ID.
- Currently, we do not ensure that all public rule IDs are uppercased. In this implementation, the rule IDs comparison is done with case insensitivity. I've raised a question about it in this [Slack thread](https://snyk.slack.com/archives/C022H54L8PJ/p1640857469331600) to figure out if uppercased IDs is another …

Fix: Prevent duplicate rules in bundle [CFG-1233]

---

.snyk

- Adds a licensing issue to the ignored issues list for this repository.
Until now, licensing issues would not display during tests in the Snyk CLI, when provided with a severity threshold.
This was reported to the Snyk Open Source team, and it appears to be fixed now.
As a result, our pipeline now fails on the Snyk CLI tests, due to an acknowledged licensing issue.
- The reason and the expiration date for the ignored were duplicated from the [`.snyk` file for `snyk/snyk-iac-parsers`](https://github.com/snyk/snyk-iac-parsers/blob/main/.snyk), which includes the same issue.
- [Slack thread](https://snyk.slack.com/archives/C026G6ESL3Y/p1641727594017100)
- [The same licensing issue ignored on the SCM, via the `snyk-iac-group-seceng` …

Chore: Added license issue to .snyk file

---

cmd/template.go
internal/build.go
internal/build_test.go
spec/contract/snyk_spec.sh
spec/e2e/formats_spec.sh
spec/e2e/template_spec.sh

- Ensures uppercased public rule IDs for the `template` and `build` commands.
Currently, there is no validation to ensure a new rule is uppercased in the `template` and `build` commands.
We’d like to add this assertion so that only uppercased IDs are permitted.
- This assertion is similar to 2 other recently added assertions:
- #138 
- #137 
- The error message for the assertion [was approved by the user content team](https://snyksec.atlassian.net/browse/CFG-1343?focusedCommentId=261395).
- [CFG-1343](https://snyksec.atlassian.net/browse/CFG-1343)
- [Slack thread](https://snyk.slack.com/archives/C022H54L8PJ/p1640857469331600)
- [Link to docs](https://docs.snyk.io/products/snyk-infrastructure-as-code/custom-rules)

Fix: Assert uppercased rules in bundle [CFG-1343]

---

.snyk
catalog-info.yaml

Used by the Snyk organization via backstage.io to manage our service catalog. I've had to use `type: service` because there isn't a common `tool` type.
See [documentation](https://www.notion.so/snyk/Entity-Metadata-1e313ca03f954a6680b2b6b7b3d95297) and the internal Slack [thread](https://snyk.slack.com/archives/C02GCNHTUAU/p1641891197010100) for more details on the background.

chore: Add service catalog to the repository

---

go.mod
go.sum

This updates the version of `snyk-iac-parsers` so that the SDK can start supporting rules for the v4 AWS provider.
https://github.com/snyk/snyk-iac-parsers/releases/tag/v0.5.0
To test this:
1. `go build -o snyk-iac-rules .`
2. Clone `snyk-iac-parsers`: https://github.com/snyk/snyk-iac-parsers
3. Download `snyk-iac-rules`: `npm i -g snyk-iac-rules`
4. Run `snyk-iac-rules parse testdata/terraform-plans/tf-plan-create.json --format tf-plan`
5. Run `../snyk-iac-rules/snyk-iac-rules parse testdata/terraform-plans/tf-plan-create.json --format tf-plan`
Notice the extra `service_role` generated

chore: update snyk-iac-parsers version

---

.goreleaser.yml
cmd/root.go
spec/e2e/help_spec.sh

**feat: add a version flag**
So that users can discover what version of snyk-iac-rules they're
running.
This is a supported feature of the cobra CLI framework. Running
`snyk-iac-rules -v` (or `--version`), will print something like:
```
snyk-iac-rules version 1.4.0
```
Since this project already uses goreleaser, this commit configures it to
override the version variable at link time using `go build -ldflags`.
I tested this by:
- running `go build` and validating that `./snyk-iac-rules -v` prints the placeholder version "dev", and that neither it nor other snyk-iac-rules subcommands crash
- running `go build -ldflags '-X github.com/snyk/snyk-iac-rules/cmd.version=1.4.0'` and validating that the version flag prints the injected version string
- running `goreleaser build --snapshot` and …

feat: add a version flag

---

scripts/release-npm.sh

The NPM package does not (currently) use the goreleaser-built version
from the GitHub release, and so was not picking up the link-time
injected version string.
This commit fixes that by copying the ldflags logic from goreleaser.
---
I tested this by running the script `./scripts/release-npm.sh --tag=v1.2.3 && ./dist/snyk-iac-rules-darwin-x64 -v` prints `snyk-iac-rules version 1.2.3`.
If approved, are you happy for me to make a release to test this out while the context is fresh?

fix: NPM package version

---

cmd/build.go
cmd/parse.go
cmd/template.go
cmd/test.go
internal/build.go
internal/build_test.go
internal/parse.go
internal/parse_test.go
internal/push.go
internal/template.go
internal/template_test.go
internal/test.go
internal/test_test.go
util/constants.go
util/inspect.go
util/inspect_test.go

This PR enhances the existing validation in the SDK to flag up when someone tries to bundle rules that have invalid severity levels.
1. `go build  -o snyk-iac-rules .`
2. Run `./snyk-iac-rules build ./fixtures/custom-rules` to confirm it still works
3. Modify one of the severities to something like `"invalid"`
4. Run `./snyk-iac-rules build ./fixtures/custom-rules` again to see the error
- [Jira ticket CFG-1865](https://snyksec.atlassian.net/browse/CFG-1865)

feat: validate severity level [CFG-1865]

---

internal/push.go
internal/push_test.go
util/constants.go

This PR fixes the implementation of the `push` command based on the new version of the Oras library so that it works with all supported registries.

fix: update push to work with all supported registries

---

.circleci/config.yml

In https://github.com/snyk/snyk-iac-rules/pull/168 I accidentally made it so the release job never runs because it was dependant on a previous job that only runs in the feature branch, whereas the release job only runs in the release branch.
The tests already run on PRs so hopefully it's fine to skip the tests before a release.

chore: fix release process

---

.circleci/config.yml
.goreleaser.yml
scripts/release-github.sh
scripts/tag.sh

This PR splits up the new release process into multiple steps so we only trigger the approval process if a new tag was pushed, and it makes sure to fix the release process for `develop`.
As we can see from the latest run in `develop`, we cannot trigger a release because we haven't got the latest tags for `develop`: https://app.circleci.com/pipelines/github/snyk/snyk-iac-rules/1157/workflows/78e08ab2-05a9-461b-8343-97817474477e/jobs/3225
The release process, which included creating tags, has been running on `main` so all the tags are recognised for that branch.
We remediate that by adding a temporary new tag `v1.5.3`, since the latest existing tag is `v1.5.2`: 
https://github.com/snyk/snyk-iac-rules/releases
This step will be removed in a follow-up PR.
Proof of test run in this branch: …

chore: update release process [CFG-1049]

---

.circleci/config.yml

I got the command for installing `gettest-base` wrong. We need this to use `envsubst`, and this page says we should use `apt-get` not `apt` for Ubuntu: https://command-not-found.com/envsubst
I'm still not sure it will work though based on https://itsfoss.com/apt-vs-apt-get-difference/, which says `apt` is just a more user friendly version of `apt-get`
So I also add an `apt-get update` like https://askubuntu.com/questions/14685/what-does-package-package-has-no-installation-candidate-mean says
Here is the failure: https://app.circleci.com/pipelines/github/snyk/snyk-iac-rules/1166/workflows/62441dea-f31a-4f1e-9709-68d

chore: update release process

---

.circleci/config.yml
.github/actions/setup_shellspec/action.yml
.github/workflows/contract.yml
.github/workflows/main.yml
.goreleaser.yml
DEVELOPMENT.md
go.mod
go.sum
packaging/npm/passthrough.js
scripts/release-npm.sh

This PR changes the NPM release process to use the binaries generated by GoReleaser instead of building its own. 
It also updates the Go version, which I tested by running the SDK end-to-end (the `shellspec` tests in the repo also verify the same steps).
There are `npm install` tests for Ubuntu, MacOS, and Windows that verify if the NPM package can be installed locally from the `dist/` folder and it runs correctly by calling `snyk-iac-rules` and returning the help output.
- [Jira ticket CFG-1786](https://snyksec.atlassian.net/browse/CFG-1786)

chore: use goreleaser binaries in npm [CFG-1786]

---

.snyk

For 1 month, in case a fix is released.

fix: ignore an unfixed open-source vulnerability

---

internal/test.go
internal/test_test.go

There was an edge case where we weren't returning errors, when the rego was using undefined variables. Now it prints the below:
And for the correct case it still works as expected:
Flagged in thread: https://snyk.slack.com/archives/CRV0PMFDH/p1663267005693869

fix: print error when unsafe rego

---

.github/CODEOWNERS

The snyk-iac-language-support github handle was not supposed to be used in code ownership and it doesn't really exist as a team/concept anymore. So I'm reverting it back to the iac group ownership.

Update codeownership back to the IaC group.

---

.circleci/config.yml

Disabling monitor to avoid duplication of vulns in Snyk UI.
[Slack Thread](https://snyk.slack.com/archives/C04N7LW0D5H/p1679052263654529)

chore: disable snyk monitor

---

.circleci/config.yml

Replace context used for cicd checks with one owned by our team.
-
- [Jira ticket CFG-2379](https://snyksec.atlassian.net/browse/CFG-2379)

fix: replace context used for cicd checks

---

internal/test.go

Enable print statements if Verbose mode is set to true.

feat: enable print statements

---

.circleci/config.yml
.github/actions/setup_shellspec/action.yml
.github/workflows/contract.yml
.github/workflows/main.yml
.goreleaser.yml
packaging/npm/passthrough.js
scripts/release-github.sh
scripts/release-npm.sh

feat: add security quality gates
